# model
model_name_or_path: /mnt/zzb6data/peixunban/zzb6/home/swZheng/OLMo/tmp/output-1B-infer_model-step120   # your_path/olmo-1b  # 需要个性化设置
trust_remote_code: true

# method
stage: sft
do_train: true
finetuning_type: full  #lora
lora_target: q_proj,v_proj  # 这里看Default module

# #ddp
# ddp_timeout: 180000000
# deepspeed: examples/deepspeed/ds_z3_config.json
# dataset
dataset: tulu-v2 #identity,  identity, adgen_local, alpa1, alpa2, gpt1, gpt2, in1, in2
cutoff_len: 1024
# max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 32

# output
output_dir: output/olmo-1b-sft-a100-tulu-v4  # 需要个性化设置
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true
# # wandb
# report_to: wandb
# run_name: sw_sft_a100_test2 # 可选

# train
per_device_train_batch_size: 2 # 每个设备（如每张 GPU）上的训练批大小，表示在单次前向和反向传播中，每个设备上处理的样本数量
gradient_accumulation_steps: 8  # 梯度累积步数，即经过多少步累积后才进行一次梯度更新，有效批大小 = per_device_train_batch_size × gradient_accumulation_steps × GPU数量
learning_rate: 0.0001
num_train_epochs: 3.0           # 训练轮数，即整个数据集被模型遍历的次数。
lr_scheduler_type: cosine       #学习率调度器类型，控制学习率的衰减策略。余弦退火策略，学习率从初始值逐渐减小。
warmup_steps: 1000 # 0.1
fp16: true

# eval
val_size: 0.1
per_device_eval_batch_size: 2
# evaluation_strategy: steps
eval_steps: 500
